
name: ai_tutor_starter
description: AI Language Tutor Starter App
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.15.0
  firebase_core: ^2.28.0
  firebase_auth: ^4.20.0
  http: ^1.2.0
  provider: ^6.1.1
  flutter_markdown: ^0.6.18
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.2
  flutter_dotenv: ^5.1.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
