
name: ai_tutor_starter
description: AI Language Tutor Starter App
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  http: ^1.1.0
  firebase_core: ^2.24.0
  firebase_auth: ^4.5.0
  cloud_firestore: ^5.14.0
  firebase_storage: ^11.3.0
  provider: ^6.0.6
  fluttertoast: ^8.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
