name: Build App Bundle

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'
    - run: flutter pub get
    - run: flutter build appbundle --release
    - name: Upload Bundle
      uses: actions/upload-artifact@v4
      with:
        name: app-bundle
        path: build/app/outputs/bundle/release/*.aab
