name: Build APK with Artifact

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'
    - run: flutter pub get
    - run: flutter build apk --release
    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ai-tutor-apk
        path: build/app/outputs/flutter-apk/app-release.apk
        if-no-files-found: error
