name: Build APK

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'
    - run: flutter pub get
    - name: Build APK with debug info
      run: |
        flutter build apk --release --verbose
        ls -la build/app/outputs/flutter-apk/
        echo "APK files:"
        find . -name "*.apk" -type f
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: build/app/outputs/flutter-apk/*.apk
        if-no-files-found: error
