name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'

    - name: Create proper Flutter structure
      run: |
        # Сохраняем наши файлы
        mkdir temp_backup
        cp -r lib temp_backup/
        cp pubspec.yaml temp_backup/
        cp -r assets temp_backup/ 2>/dev/null || true
        
        # Создаем новый проект с правильной структурой
        flutter create --org com.example --project-name ai_tutor .
        
        # Восстанавливаем наши файлы
        rm -rf lib
        cp -r temp_backup/lib .
        cp temp_backup/pubspec.yaml .
        cp -r temp_backup/assets . 2>/dev/null || true
        rm -rf temp_backup
        
        # Обновляем зависимости
        flutter pub get

    - name: Build APK
      run: flutter build apk --release

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: build/app/outputs/flutter-apk/app-release.apk
